AWSTemplateFormatVersion: 2010-09-09
Description: Some description for this stack

# ---------- Parameters -------------------------------------------------------
Parameters:
  CertificateArn:
    Type: String
    # This certificate is deleted and must be updated when it is created again
    Default: arn:aws:acm:us-east-1:558043415147:certificate/c0f68e5a-a4d4-4332-85a0-9a41d9e970e7
    Description: Certificate must be created before CloudFormation stack so the value is fixed
  BucketName:
    Type: String
    Default: bw-hosting-https-cloudflare
  DomainName:
    Type: String
    Default: bw-https.al-un.fr

# ---------- Resources lists --------------------------------------------------
Resources:
  S3Hosting:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

  CDNOriginIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "Cloudfront Origin identity for ${DomainName}"

  CDN:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: True
          TargetOriginId: !Sub "S3-origin-${S3Hosting}"
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: True
        HttpVersion: http2
        IPV6Enabled: True
        Origins:
          - DomainName: !GetAtt S3Hosting.RegionalDomainName
            Id: !Sub "S3-origin-${S3Hosting}"
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CDNOriginIdentity}"
        PriceClass: PriceClass_100 # PriceClass_100 / PriceClass_200 / PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          MinimumProtocolVersion: TLSv1.2_2018
          SslSupportMethod: sni-only

  S3HostingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Hosting
      PolicyDocument:
        Statement:
          - Action:
              - "s3:GetObject"
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CDNOriginIdentity}"
            Resource: !Sub "arn:aws:s3:::${S3Hosting}/*"
        Version: "2012-10-17"

Outputs:
  CloudFrontID:
    Value: !Ref CDN
    Description: CloudFront ID
  CloudFrontURL:
    Value: !GetAtt CDN.DomainName
    Description: CloudFront URL for updating DNS record
