AWSTemplateFormatVersion: 2010-09-09

# ---------- Parameters -------------------------------------------------------
Parameters:
  DomainName:
    Type: String
    Default: bw-domain-aws.al-un.fr
  RootDomainName:
    Type: String
    Default: al-un.fr.

# ---------- Mappings ---------------------------------------------------------
Mappings:
  S3Regions:
    ap-northeast-1:
      ZoneId: Z2M4EHUR26P7ZW
      Endpoint: s3-website-ap-northeast-1.amazonaws.com
    eu-west-3:
      ZoneId: Z3R1K369G5AVDG
      Endpoint: s3-website.eu-west-3.amazonaws.com
    us-east-1:
      ZoneId: Z3AQBSTGFYJSTF
      Endpoint: s3-website-us-east-1.amazonaws.com

# ---------- Resources lists --------------------------------------------------
Resources:
  S3Hosting:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref DomainName
      WebsiteConfiguration:
        ErrorDocument: 404.html
        IndexDocument: index.html

  S3HostingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Hosting
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Join
              - ""
              - - "arn:aws:s3:::"
                - !Ref S3Hosting
                - /*

  S3Redirection:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: BucketOwnerFullControl
      BucketName: !Sub www.${DomainName}
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref S3Hosting

  DNSEntries:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Ref RootDomainName
      RecordSets:
        - AliasTarget:
            HostedZoneId: !FindInMap [S3Regions, !Ref "AWS::Region", ZoneId]
            DNSName: !FindInMap [S3Regions, !Ref "AWS::Region", Endpoint]
          Name: !Ref DomainName
          Type: A
        - Name: !Sub www.${DomainName}
          ResourceRecords:
            - !GetAtt S3Redirection.DomainName
          Type: CNAME
          TTL: 900